# fly.toml app configuration file generated for habits-tuminzee on 2024-11-26T18:08:20+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'habits-tuminzee'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.22.4'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
